name: Build .NET Solution
on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Load env variables from vars.env
      run: |
        set -a
        source ./.github/variables/vars.env
        set +a
      shell: bash

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Clean solution
      run: dotnet clean ${{ env.PROJECT_PATH }}

    - name: Restore dependencies
      run: dotnet restore ${{ env.PROJECT_PATH }}

    - name: Build solution
      run: dotnet build ${{ env.PROJECT_PATH }} --no-restore --configuration Release