name: Deploy to Render

on:
  workflow_call:
    secrets:
      DOCKERHUB_PASSWORD:
        required: true
      RENDER_API_KEY:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: delower
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        run: docker build -t delower/stack-practice:latest .

      - name: Push Docker image to Docker Hub
        run: docker push delower/stack-practice:latest

      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          curl -X POST https://api.render.com/deploy/srv-d1l4nnur433s73d8uv10 \
          -H "Authorization: Bearer $RENDER_API_KEY"
