name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
env:
  PROJECT_PATH: EFCoreDemo/EFCoreDemo.sln

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore $PROJECT_PATH
      
    - name: Build
      run: dotnet build $PROJECT_PATH --no-restore

    - name: Run all tests (with report)
      run: dotnet test EFCoreDemo/xUnitTests/xUnitTests.csproj --no-build --configuration Release --logger "trx"

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: '**/TestResults/*.trx'
