name: .NET CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  PROJECT_PATH: EFCoreDemo/EFCoreDemo.sln

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name:️ Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Clean solution
      run: dotnet clean $PROJECT_PATH

    - name: Restore dependencies
      run: dotnet restore $PROJECT_PATH

    - name: Build solution
      run: dotnet build $PROJECT_PATH --no-restore --configuration Release

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name:️ Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore $PROJECT_PATH

    - name: Run tests
      run: dotnet test $PROJECT_PATH --configuration Release --logger "trx"

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: '**/TestResults/*.trx'
