name: .NET CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-job:
    uses: ./.github/workflows/build.yml

  test-job:
    needs: build-job
    uses: ./.github/workflows/test.yml
  sonar-job:
    needs: test-job
    uses: ./.github/workflows/sonar.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
