name: Run Unit Tests
on:
  workflow_call:

env:
  PROJECT_PATH: EFCoreDemo/EFCoreDemo.sln

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore $PROJECT_PATH

    - name: Run unit tests
      run: dotnet test $PROJECT_PATH --no-build --configuration Release --verbosity normal

    - name: 📤 Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: '**/TestResults/*.trx'