name: Run Unit Tests
on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Load env variables from vars.env
      run: |
        set -a
        source variables/vars.env
        set +a
      shell: bash

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore ${{ env.PROJECT_PATH }}

    - name: Run unit tests
      run: dotnet test ${{ env.PROJECT_PATH }} --configuration Release --verbosity normal

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: '**/TestResults/*.trx'